// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | CtaSlice
  | CuisinesSlice
  | SliderDemoSlice
  | HallsSlice
  | IntroTextSlice
  | RoomsSlice
  | RoomCategoriesSlice
  | OurStorySlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for introReveal documents
 */
interface IntrorevealDocumentData {
  /**
   * demoIntro field in *introReveal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introreveal.demointro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  demointro: prismic.RichTextField;
}

/**
 * introReveal document from Prismic
 *
 * - **API ID**: `introreveal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntrorevealDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IntrorevealDocumentData>,
    "introreveal",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | IntrorevealDocument;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * ctaimg field in *Cta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.ctaimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ctaimg: prismic.ImageField<never>;

  /**
   * ctaheading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.ctaheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ctaheading: prismic.RichTextField;

  /**
   * ctadescription field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.ctadescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ctadescription: prismic.RichTextField;

  /**
   * ctalink field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.ctalink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctalink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ctalinktext field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.ctalinktext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ctalinktext: prismic.KeyTextField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *Cuisines → Default → Primary*
 */
export interface CuisinesSliceDefaultPrimary {
  /**
   * Heading field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * description field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * dininglink field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.dininglink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dininglink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * linktext field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.linktext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  linktext: prismic.KeyTextField;

  /**
   * headshot field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.headshot
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  headshot: prismic.ImageField<never>;

  /**
   * chefname field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.chefname
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  chefname: prismic.RichTextField;

  /**
   * chef expertise field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.chef_expertise
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  chef_expertise: prismic.RichTextField;

  /**
   * rightimg field in *Cuisines → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cuisines.default.primary.rightimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightimg: prismic.ImageField<never>;
}

/**
 * Default variation for Cuisines Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CuisinesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CuisinesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cuisines*
 */
type CuisinesSliceVariation = CuisinesSliceDefault;

/**
 * Cuisines Shared Slice
 *
 * - **API ID**: `cuisines`
 * - **Description**: Cuisines
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CuisinesSlice = prismic.SharedSlice<
  "cuisines",
  CuisinesSliceVariation
>;

/**
 * Primary content in *Halls → Default → Primary*
 */
export interface HallsSliceDefaultPrimary {
  /**
   * Heading field in *Halls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: halls.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Image field in *Halls → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: halls.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * secondcol_img field in *Halls → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: halls.default.primary.secondcol_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  secondcol_img: prismic.ImageField<never>;

  /**
   * thirdcol_img field in *Halls → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: halls.default.primary.thirdcol_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thirdcol_img: prismic.ImageField<never>;

  /**
   * thirdDescription field in *Halls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: halls.default.primary.thirddescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  thirddescription: prismic.RichTextField;
}

/**
 * Default variation for Halls Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HallsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HallsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Halls*
 */
type HallsSliceVariation = HallsSliceDefault;

/**
 * Halls Shared Slice
 *
 * - **API ID**: `halls`
 * - **Description**: Halls
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HallsSlice = prismic.SharedSlice<"halls", HallsSliceVariation>;

/**
 * Primary content in *Hero → Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * hero img field in *Hero → Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_img: prismic.ImageField<never>;

  /**
   * sub heading field in *Hero → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * paragraph field in *Hero → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * button link field in *Hero → Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button lable field in *Hero → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_lable
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_lable: prismic.KeyTextField;
}

/**
 * Hero variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IntroText → Default → Primary*
 */
export interface IntroTextSliceDefaultPrimary {
  /**
   * revealingText field in *IntroText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text.default.primary.revealingtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  revealingtext: prismic.RichTextField;
}

/**
 * Default variation for IntroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroText*
 */
type IntroTextSliceVariation = IntroTextSliceDefault;

/**
 * IntroText Shared Slice
 *
 * - **API ID**: `intro_text`
 * - **Description**: IntroText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroTextSlice = prismic.SharedSlice<
  "intro_text",
  IntroTextSliceVariation
>;

/**
 * Primary content in *OurStory → Default → Primary*
 */
export interface OurStorySliceDefaultPrimary {
  /**
   * storyheading field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.storyheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  storyheading: prismic.RichTextField;

  /**
   * headingtwo field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.headingtwo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headingtwo: prismic.RichTextField;

  /**
   * outstoryimg field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.outstoryimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  outstoryimg: prismic.ImageField<never>;

  /**
   * headingthree field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.headingthree
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headingthree: prismic.RichTextField;

  /**
   * storydiscription field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.storydiscription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  storydiscription: prismic.RichTextField;

  /**
   * storyTitle field in *OurStory → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_story.default.primary.storytitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  storytitle: prismic.RichTextField;
}

/**
 * Default variation for OurStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurStorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurStorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurStory*
 */
type OurStorySliceVariation = OurStorySliceDefault;

/**
 * OurStory Shared Slice
 *
 * - **API ID**: `our_story`
 * - **Description**: OurStory
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurStorySlice = prismic.SharedSlice<
  "our_story",
  OurStorySliceVariation
>;

/**
 * Item in *RoomCategories → Default → Primary → Categories*
 */
export interface RoomCategoriesSliceDefaultPrimaryCategoriesItem {
  /**
   * roomimage field in *RoomCategories → Default → Primary → Categories*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.categories[].roomimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  roomimage: prismic.ImageField<never>;

  /**
   * title field in *RoomCategories → Default → Primary → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.categories[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * bookinglink field in *RoomCategories → Default → Primary → Categories*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.categories[].bookinglink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  bookinglink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * linktext field in *RoomCategories → Default → Primary → Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.categories[].linktext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  linktext: prismic.KeyTextField;
}

/**
 * Primary content in *RoomCategories → Default → Primary*
 */
export interface RoomCategoriesSliceDefaultPrimary {
  /**
   * roomsHeading field in *RoomCategories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.roomsheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  roomsheading: prismic.RichTextField;

  /**
   * Categories field in *RoomCategories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: room_categories.default.primary.categories[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<
    Simplify<RoomCategoriesSliceDefaultPrimaryCategoriesItem>
  >;
}

/**
 * Default variation for RoomCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomCategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoomCategoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoomCategories*
 */
type RoomCategoriesSliceVariation = RoomCategoriesSliceDefault;

/**
 * RoomCategories Shared Slice
 *
 * - **API ID**: `room_categories`
 * - **Description**: RoomCategories
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomCategoriesSlice = prismic.SharedSlice<
  "room_categories",
  RoomCategoriesSliceVariation
>;

/**
 * Primary content in *Rooms → Default → Primary*
 */
export interface RoomsSliceDefaultPrimary {
  /**
   * heading field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * subtext field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;

  /**
   * button field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * view rooms field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.view_rooms
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  view_rooms: prismic.KeyTextField;

  /**
   * roomimage field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.roomimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  roomimage: prismic.ImageField<never>;

  /**
   * roomimagetwo field in *Rooms → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rooms.default.primary.roomviewtwo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  roomviewtwo: prismic.ImageField<never>;
}

/**
 * Default variation for Rooms Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoomsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Rooms*
 */
type RoomsSliceVariation = RoomsSliceDefault;

/**
 * Rooms Shared Slice
 *
 * - **API ID**: `rooms`
 * - **Description**: Rooms
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomsSlice = prismic.SharedSlice<"rooms", RoomsSliceVariation>;

/**
 * Primary content in *SliderDemo → Default → Primary*
 */
export interface SliderDemoSliceDefaultPrimary {
  /**
   * sliderimg field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.sliderimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sliderimg: prismic.ImageField<never>;

  /**
   * heading field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * description field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * rightimg field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.rightimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightimg: prismic.ImageField<never>;

  /**
   * rightheading field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.rightheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rightheading: prismic.RichTextField;

  /**
   * rightdescription field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.rightdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rightdescription: prismic.RichTextField;

  /**
   * rightimgtwo field in *SliderDemo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_demo.default.primary.rightimgtwo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightimgtwo: prismic.ImageField<never>;
}

/**
 * Default variation for SliderDemo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderDemoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderDemoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SliderDemo*
 */
type SliderDemoSliceVariation = SliderDemoSliceDefault;

/**
 * SliderDemo Shared Slice
 *
 * - **API ID**: `slider_demo`
 * - **Description**: SliderDemo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderDemoSlice = prismic.SharedSlice<
  "slider_demo",
  SliderDemoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      IntrorevealDocument,
      IntrorevealDocumentData,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CuisinesSlice,
      CuisinesSliceDefaultPrimary,
      CuisinesSliceVariation,
      CuisinesSliceDefault,
      HallsSlice,
      HallsSliceDefaultPrimary,
      HallsSliceVariation,
      HallsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      IntroTextSlice,
      IntroTextSliceDefaultPrimary,
      IntroTextSliceVariation,
      IntroTextSliceDefault,
      OurStorySlice,
      OurStorySliceDefaultPrimary,
      OurStorySliceVariation,
      OurStorySliceDefault,
      RoomCategoriesSlice,
      RoomCategoriesSliceDefaultPrimaryCategoriesItem,
      RoomCategoriesSliceDefaultPrimary,
      RoomCategoriesSliceVariation,
      RoomCategoriesSliceDefault,
      RoomsSlice,
      RoomsSliceDefaultPrimary,
      RoomsSliceVariation,
      RoomsSliceDefault,
      SliderDemoSlice,
      SliderDemoSliceDefaultPrimary,
      SliderDemoSliceVariation,
      SliderDemoSliceDefault,
    };
  }
}
