// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  our_story: dynamic(() => import("./OurStory")),
  rooms: dynamic(() => import("./Rooms")),
};
